[project]
name = "exploit1"
version = "0.1.0"
description = ""
authors = [
    {name = "claustra01",email = "shinya430.g@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pwntools (>=4.14.1,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
